packages:
- '.'
extra-deps:
- beam-0.3.2.0
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
- convertible-1.1.1.0
- git: https://github.com/tathougies/beam.git
  commit: 12437153ff715ae96bc7c3ffe5db39e67225a8ca
  subdirs:
    - beam-core

allow-newer: true
resolver: lts-13.26
